#!/usr/bin/env node

/**
 * Test suite for Issue Consolidation Script - Dry Run Functionality
 * 
 * This test verifies that:
 * 1. The script handles 'dry-run' action correctly
 * 2. Report is generated in dry-run mode
 * 3. No mutations occur (no issues are actually closed)
 * 4. Exit code is 0 on success
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

class ConsolidationDryRunTest {
  constructor() {
    this.testResults = {
      passed: 0,
      failed: 0,
      total: 0,
      errors: []
    };
    this.testReportPath = path.join(process.cwd(), 'test-consolidation-report.json');
  }

  runTest(name, testFn) {
    this.testResults.total++;
    try {
      testFn();
      this.testResults.passed++;
      console.log(`  ✅ ${name}`);
      return true;
    } catch (error) {
      this.testResults.failed++;
      this.testResults.errors.push({ name, error: error.message });
      console.log(`  ❌ ${name}`);
      console.log(`     Error: ${error.message}`);
      return false;
    }
  }

  async runAllTests() {
    console.log('🧪 Running Consolidation Dry-Run Tests\n');
    
    // Cleanup any existing test files
    this.cleanup();

    // Test 1: Verify script file exists
    this.runTest('Script file exists', () => {
      const scriptPath = path.join(process.cwd(), 'scripts/consolidate-issues-to-hierarchy.js');
      if (!fs.existsSync(scriptPath)) {
        throw new Error('Consolidation script not found');
      }
    });

    // Test 2: Verify script can be loaded as module
    this.runTest('Script can be loaded as module', () => {
      const IssueConsolidator = require('../scripts/consolidate-issues-to-hierarchy.js');
      if (typeof IssueConsolidator !== 'function') {
        throw new Error('Script does not export a constructor function');
      }
    });

    // Test 3: Verify IssueConsolidator class can be instantiated
    this.runTest('IssueConsolidator can be instantiated', () => {
      const IssueConsolidator = require('../scripts/consolidate-issues-to-hierarchy.js');
      const consolidator = new IssueConsolidator();
      if (!consolidator) {
        throw new Error('Failed to instantiate IssueConsolidator');
      }
      if (typeof consolidator.generateReport !== 'function') {
        throw new Error('generateReport method not found');
      }
      if (typeof consolidator.closeAutoGeneratedIssues !== 'function') {
        throw new Error('closeAutoGeneratedIssues method not found');
      }
    });

    // Test 4: Verify generateReport creates report file
    this.runTest('generateReport creates report file', () => {
      const IssueConsolidator = require('../scripts/consolidate-issues-to-hierarchy.js');
      const consolidator = new IssueConsolidator();
      
      // Mock the issue data since we can't call GitHub API in tests
      consolidator.autoGeneratedIssues = [];
      consolidator.hierarchicalIssues = [];
      consolidator.toClose = [];
      consolidator.toKeep = [];
      
      const report = consolidator.generateReport();
      
      if (!fs.existsSync('issue-consolidation-report.json')) {
        throw new Error('Report file was not created');
      }
      
      const content = fs.readFileSync('issue-consolidation-report.json', 'utf8');
      const reportData = JSON.parse(content);
      
      if (!reportData.summary) {
        throw new Error('Report missing summary section');
      }
      if (!reportData.timestamp) {
        throw new Error('Report missing timestamp');
      }
      
      // Cleanup
      fs.unlinkSync('issue-consolidation-report.json');
    });

    // Test 5: Verify dry-run mode doesn't throw errors
    this.runTest('Dry-run mode executes without errors', () => {
      const IssueConsolidator = require('../scripts/consolidate-issues-to-hierarchy.js');
      const consolidator = new IssueConsolidator();
      
      // Mock the issue data
      consolidator.autoGeneratedIssues = [
        { number: 1, title: 'Test Issue 1', labels: [{ name: 'todo' }], html_url: 'http://test', created_at: new Date().toISOString() },
        { number: 2, title: 'Test Issue 2', labels: [{ name: 'todo' }], html_url: 'http://test', created_at: new Date().toISOString() }
      ];
      consolidator.hierarchicalIssues = [];
      consolidator.toClose = consolidator.autoGeneratedIssues;
      consolidator.toKeep = [];
      
      // This should not throw
      consolidator.generateReport();
      consolidator.closeAutoGeneratedIssues(true); // dry-run = true
      consolidator.displaySummary();
      
      // Verify report was created
      if (!fs.existsSync('issue-consolidation-report.json')) {
        throw new Error('Report not generated in dry-run mode');
      }
      
      // Cleanup
      fs.unlinkSync('issue-consolidation-report.json');
    });

    // Test 6: Verify closeAutoGeneratedIssues respects dry-run flag
    this.runTest('closeAutoGeneratedIssues respects dry-run flag', () => {
      const IssueConsolidator = require('../scripts/consolidate-issues-to-hierarchy.js');
      const consolidator = new IssueConsolidator();
      
      // Mock the issue data
      consolidator.toClose = [
        { number: 1, title: 'Test Issue 1', labels: [{ name: 'todo' }] },
        { number: 2, title: 'Test Issue 2', labels: [{ name: 'todo' }] }
      ];
      
      // Capture console output to verify dry-run messages
      const originalLog = console.log;
      let output = '';
      console.log = (msg) => { output += msg + '\n'; };
      
      consolidator.closeAutoGeneratedIssues(true); // dry-run = true
      
      console.log = originalLog;
      
      // Verify dry-run messaging appears
      if (!output.includes('DRY RUN') && !output.includes('dry run')) {
        throw new Error('Dry-run messaging not found in output');
      }
    });

    // Test 7: Verify report structure is correct
    this.runTest('Report has correct structure', () => {
      const IssueConsolidator = require('../scripts/consolidate-issues-to-hierarchy.js');
      const consolidator = new IssueConsolidator();
      
      consolidator.autoGeneratedIssues = [
        { number: 1, title: 'Test', labels: [{ name: 'todo' }], html_url: 'http://test', created_at: new Date().toISOString() }
      ];
      consolidator.hierarchicalIssues = [];
      consolidator.toClose = consolidator.autoGeneratedIssues;
      consolidator.toKeep = [];
      
      const report = consolidator.generateReport();
      
      // Verify report structure
      if (!report.summary) throw new Error('Missing summary');
      if (!report.issues_to_close) throw new Error('Missing issues_to_close');
      if (!report.hierarchical_issues) throw new Error('Missing hierarchical_issues');
      if (!report.issues_to_keep) throw new Error('Missing issues_to_keep');
      
      if (typeof report.summary.total_open_issues !== 'number') {
        throw new Error('Invalid total_open_issues in summary');
      }
      if (typeof report.summary.auto_generated_to_close !== 'number') {
        throw new Error('Invalid auto_generated_to_close in summary');
      }
      
      // Cleanup
      fs.unlinkSync('issue-consolidation-report.json');
    });

    // Display results
    console.log('\n' + '='.repeat(70));
    console.log('📊 Test Results');
    console.log('='.repeat(70));
    console.log(`Total Tests: ${this.testResults.total}`);
    console.log(`Passed: ${this.testResults.passed} ✅`);
    console.log(`Failed: ${this.testResults.failed} ❌`);
    console.log('='.repeat(70));

    if (this.testResults.failed > 0) {
      console.log('\n❌ Failed Tests:');
      this.testResults.errors.forEach(({ name, error }) => {
        console.log(`  - ${name}: ${error}`);
      });
      process.exit(1);
    } else {
      console.log('\n✅ All tests passed!');
      process.exit(0);
    }
  }

  cleanup() {
    const filesToClean = [
      'issue-consolidation-report.json',
      'test-consolidation-report.json',
      'CONFIRM_CLOSE_ISSUES.txt'
    ];
    
    filesToClean.forEach(file => {
      const filePath = path.join(process.cwd(), file);
      if (fs.existsSync(filePath)) {
        fs.unlinkSync(filePath);
      }
    });
  }
}

// Run tests if called directly
if (require.main === module) {
  const test = new ConsolidationDryRunTest();
  test.runAllTests().catch(error => {
    console.error('Fatal error:', error);
    process.exit(1);
  });
}

module.exports = ConsolidationDryRunTest;
